config = {
    'listeners': {
        'default': {
            'type': 'tcp',
            'bind': '0.0.0.0:1883'
        },
    },
    'sys_interval': 10,
    'topic-check': {
        'enabled': False  # Disable topic_check plugin
    }
}
